# this is name of all jobs on github actions bot
name: "Build and push to dev branch"

# param which describe main repository
on:
  push:
    branches:
      - "main"

# only for a creation and editing new branches during auto-mode process
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Commit and push to dev
        env:
          PAT: ${{ secrets.PRO_16_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan dev
          git reset

          shopt -s extglob
          rm -rf !(dist|.git)
          shopt -u extglob

          cp -r dist/* .
          rm -rf dist

          git add -A
          git commit -m "Build artifacts"

          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git push -u origin dev --force
